'use client';

import { getCurrentWindow, LogicalPosition, LogicalSize} from '@tauri-apps/api/window';

import React, { useState, useEffect, useCallback, use } from 'react';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { TooltipProvider } from '@/components/ui/tooltip';
import SidebarStage from '@/components/sidebar/sidebar-stage';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useEffect(() => {
    const updateWindowSize = async () => {
      const currentWindow = await getCurrentWindow();
      await currentWindow.setSize(new LogicalSize(1000, 800)); // 设置为你需要的尺寸
    };
    updateWindowSize();
  }, []); 

  return (
    <div className="chat">
        <main className="relative overflow-hidden">
            <SidebarStage />
            {children}
            {/* <MobileFooter /> */}
        </main>
    </div>
  );
}


